;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        counsel-M-x
        dap-tooltip-mouse-motion
        electric-newline-and-maybe-indent
        indent-for-tab-command
        org-self-insert-command
        popup-kill-ring
        smart-hungry-delete-region-code
        ))

(setq mc/cmds-to-run-once
      '(
        iedit-switch-to-mc-mode
        ))
